=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT sport_shop ( shop_info, supplements, sport_accessories ) >

<!ELEMENT shop_info ( shop_name, country, city, address, phone, email, site) >
<!ATTLIST shop_info shop_id ID #REQUIRED>
<!ELEMENT shop_name ( #PCDATA ) >
<!ELEMENT country ( #PCDATA ) >
<!ELEMENT city ( #PCDATA ) >
<!ELEMENT address ( #PCDATA ) >
<!ELEMENT phone ( #PCDATA ) >
<!ELEMENT email ( #PCDATA ) >
<!ELEMENT site ( #PCDATA ) >

<!ELEMENT supplements ( supplement+ ) >
<!ELEMENT supplement (supplement_name, supplement_price, supplement_rating, taste,  packing, servings) >
<!ATTLIST supplement supplement_id CDATA #REQUIRED
			              type CDATA #REQUIRED		                                            
			              purpose CDATA #REQUIRED
			              supplement_brand CDATA #REQUIRED
			              available_in_shop  IDREFS #REQUIRED>
<!ELEMENT supplement_name ( #PCDATA ) >
<!ELEMENT supplement_price ( #PCDATA ) >
<!ATTLIST supplement_price currency CDATA #REQUIRED>
<!ELEMENT supplement_rating ( #PCDATA ) >
<!ELEMENT taste ( #PCDATA ) >
<!ELEMENT packing ( #PCDATA ) >
<!ATTLIST packing measurement_unit CDATA #REQUIRED >
<!ELEMENT servings ( #PCDATA ) >

<!ELEMENT sport_accessories (boxing_gloves+,  sport_shoes+) >

<!ELEMENT boxing_gloves ( boxing_gloves_model,boxing_gloves_price, boxing_gloves_size,  boxing_gloves_rating, boxing_gloves_material, origin) >
<!ATTLIST boxing_gloves boxing_gloves_id CDATA #REQUIRED
                                available_in_shop  IDREFS #REQUIRED>
<!ELEMENT boxing_gloves_model ( #PCDATA ) >
<!ELEMENT boxing_gloves_price ( #PCDATA ) >
<!ATTLIST  boxing_gloves_price currency CDATA #REQUIRED >
<!ELEMENT boxing_gloves_size ( #PCDATA ) >
<!ELEMENT boxing_gloves_rating ( #PCDATA ) >
<!ELEMENT boxing_gloves_material ( #PCDATA ) >
<!ELEMENT origin ( #PCDATA ) >

<!ELEMENT sport_shoes ( shoes_model, shoes_price, shoes_size, shoes_color, shoes_brand) >
<!ATTLIST sport_shoes sport_shoes_id CDATA #REQUIRED 
                                available_in_shop  IDREFS #REQUIRED>
<!ELEMENT shoes_model ( #PCDATA ) >
<!ELEMENT shoes_price ( #PCDATA ) >
<!ATTLIST shoes_price currency CDATA #REQUIRED >
<!ELEMENT shoes_size ( #PCDATA ) >
<!ELEMENT  shoes_color ( #PCDATA ) >
<!ELEMENT shoes_brand ( #PCDATA ) >

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="21"  type="Гейнъри" purpose="Стимулира покачването на тегло"  supplement_brand="Мекс" available_in_shop="N1">
      <supplement_name>Маркед мас</supplement_name>
      <supplement_price currency="лев">57.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>ванилия</taste>
      <packing measurement_unit="кг">2.225</packing>
      <servings>22 дози</servings>
    </supplement>
    <supplement supplement_id="22" type="Аминокиселини" purpose="Изгаряне на мазнини"  supplement_brand="Биотеч" available_in_shop="N1">
      <supplement_name>Аминос</supplement_name>
      <supplement_price currency="лев">68.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>10 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="20" available_in_shop="N1">
      <boxing_gloves_model>Икуша</boxing_gloves_model>
      <boxing_gloves_price currency="лев">58.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>10</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Хаябушу</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="21" available_in_shop="N1">
      <boxing_gloves_model>Спортер</boxing_gloves_model>
      <boxing_gloves_price currency="лев">56.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="20" available_in_shop="N1">
      <shoes_model>Нова</shoes_model>
      <shoes_price currency="лев">64.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="21" available_in_shop="N1">
      <shoes_model>Гернова</shoes_model>
      <shoes_price currency="лев">76.00</shoes_price>
      <shoes_size>43</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_infoo shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_infoo>
  <supplements>
    <supplement supplement_id="3"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Синтракс" available_in_shop="N1">
      <supplement_name>Матрикс</supplement_name>
      <supplement_price currency="лев">88.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>ванилия</taste>
      <packing measurement_unit="кг">2.225</packing>
      <servings>22 дози</servings>
    </supplement>
    <supplement supplement_id="4"  type="Гейнъри" purpose="Стимулира покачването на тегло"  supplement_brand="Мутант" available_in_shop="N1">
      <supplement_name>Мутант мас</supplement_name>
      <supplement_price currency="лев">140.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">5.450</packing>
      <servings>20 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="3" available_in_shop="N1">
      <boxing_gloves_model>Про стил</boxing_gloves_model>
      <boxing_gloves_price currency="лев">52.00</boxing_gloves_price>
      <boxing_gloves_size>14 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>6</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="4" available_in_shop="N1">
      <boxing_gloves_model>Протекс</boxing_gloves_model>
      <boxing_gloves_price currency="лев">56.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="3" available_in_shop="N1">
      <shoes_model>Канадия</shoes_model>
      <shoes_price currency="лев">74.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="4" available_in_shop="N1">
      <shoes_model>Дескендия</shoes_model>
      <shoes_price currency="лев">86.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="25"   type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Oптимум нутришън" available_in_shop="N1">
      <supplement_name>Креатин транспорт</supplement_name>
      <supplement_price currency="лев">38.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">0.600</packing>
      <servings>30 дози</servings>
    </supplement>
    <supplement supplement_id="26"  type="Аминокиселини" purpose="Изгаряне на мазнини"  supplement_brand="Сцитец" available_in_shop="N1">
      <supplement_name>Мега Аргинин</supplement_name>
      <supplement_price currency="лев">48.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="24" available_in_shop="N1">
      <boxing_gloves_model>Ерго молдед</boxing_gloves_model>
      <boxing_gloves_price currency="лев">75.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>9</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="25" available_in_shop="N1">
      <boxing_gloves_model>Аиба</boxing_gloves_model>
      <boxing_gloves_price currency="лев">230.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>10</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="24" available_in_shop="N1">
      <shoes_model>Екстра</shoes_model>
      <shoes_price currency="лев">54.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="25" available_in_shop="N1">
      <shoes_model>Екстра Фалкон</shoes_model>
      <shoes_price currency="лев">94.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-18.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="35"  type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Универсал" available_in_shop="N1">
      <supplement_name>Транс-Х</supplement_name>
      <supplement_price currency="лев">28.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50 дози</servings>
    </supplement>
    <supplement supplement_id="36"  type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Сцитец" available_in_shop="N1">
      <supplement_name>Витарго</supplement_name>
      <supplement_price currency="лев">48.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="34" available_in_shop="N1">
      <boxing_gloves_model>СЗ про</boxing_gloves_model>
      <boxing_gloves_price currency="лев">55.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>СЗ</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="35" available_in_shop="N1">
      <boxing_gloves_model>Аиба</boxing_gloves_model>
      <boxing_gloves_price currency="лев">230.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>10</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="34" available_in_shop="N1">
      <shoes_model>Електра</shoes_model>
      <shoes_price currency="лев">84.00</shoes_price>
      <shoes_size>45</shoes_size>
      <shoes_color>бяли</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="35" available_in_shop="N1">
      <shoes_model>Вактана</shoes_model>
      <shoes_price currency="лев">74.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="9"  type="Гейнъри" purpose="Стимулира покачването на тегло"  supplement_brand="Гаспари" available_in_shop="N1">
      <supplement_name>Реал мас</supplement_name>
      <supplement_price currency="лев">135.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">5.000</packing>
      <servings>25 дози</servings>
    </supplement>
    <supplement supplement_id="10" type="Аминокиселини" purpose="Изгаряне на мазнини"  supplement_brand="Гаспари" available_in_shop="N1">
      <supplement_name>Амино макс</supplement_name>
      <supplement_price currency="лев">48.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">0.450</packing>
      <servings>22 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="9" available_in_shop="N1">
      <boxing_gloves_model>Спорт</boxing_gloves_model>
      <boxing_gloves_price currency="лев">41.00</boxing_gloves_price>
      <boxing_gloves_size>14 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>6</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="10" available_in_shop="N1">
      <boxing_gloves_model>Праид</boxing_gloves_model>
      <boxing_gloves_price currency="лев">58.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Праид</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="9" available_in_shop="N1">
      <shoes_model>Нова</shoes_model>
      <shoes_price currency="лев">94.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>бяли</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="10" available_in_shop="N1">
      <shoes_model>Пецер</shoes_model>
      <shoes_price currency="лев">76.00</shoes_price>
      <shoes_size>45</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-20.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="39"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Oптимум нутришън" available_in_shop="N1">
      <supplement_name>Ултра</supplement_name>
      <supplement_price currency="лев">95.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">2.225</packing>
      <servings>22 дози</servings>
    </supplement>
    <supplement supplement_id="40"  type="Гейнъри" purpose="Стимулира покачването на тегло"  supplement_brand="Биотеч" available_in_shop="N1">
      <supplement_name>Карбо-Х</supplement_name>
      <supplement_price currency="лев">95.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">5.450</packing>
      <servings>20 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="38" available_in_shop="N1">
      <boxing_gloves_model>Ерго про</boxing_gloves_model>
      <boxing_gloves_price currency="лев">75.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>9</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="39" available_in_shop="N1">
      <boxing_gloves_model>Аиба про</boxing_gloves_model>
      <boxing_gloves_price currency="лев">230.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>10</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Адидас</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="38" available_in_shop="N1">
      <shoes_model>Дарт</shoes_model>
      <shoes_price currency="лев">86.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>сиви</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="39" available_in_shop="N1">
      <shoes_model>Фалкон</shoes_model>
      <shoes_price currency="лев">96.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>червени</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-19.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="37" type="Аминокиселини" purpose="Изгаряне на мазнини"  supplement_brand="Гаспари" available_in_shop="N1">
      <supplement_name>Амино х</supplement_name>
      <supplement_price currency="лев">48.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">0.450</packing>
      <servings>22 дози</servings>
    </supplement>
    <supplement supplement_id="38"  type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Универсал" available_in_shop="N1">
      <supplement_name>Креабос</supplement_name>
      <supplement_price currency="лев">48.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="36" available_in_shop="N1">
      <boxing_gloves_model>Еверласт про</boxing_gloves_model>
      <boxing_gloves_price currency="лев">50.00</boxing_gloves_price>
      <boxing_gloves_size>14 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>6</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="37" available_in_shop="N1">
      <boxing_gloves_model>Праид</boxing_gloves_model>
      <boxing_gloves_price currency="лев">58.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Праид</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="36" available_in_shop="N1">
      <shoes_model>Нова спорт</shoes_model>
      <shoes_price currency="лев">94.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>бяли</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="37" available_in_shop="N1">
      <shoes_model>Рунер</shoes_model>
      <shoes_price currency="лев">76.00</shoes_price>
      <shoes_size>45</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="31"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Сцитец" available_in_shop="N1">
      <supplement_name>Анаболик</supplement_name>
      <supplement_price currency="лев">102.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">2.225</packing>
      <servings>22 дози</servings>
    </supplement>
    <supplement supplement_id="32"  type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Универсал" available_in_shop="N1">
      <supplement_name>ККреатин Транспорт</supplement_name>
      <supplement_price currency="лев">58.00</supplement_price>
      <supplement_rating>9</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="30" available_in_shop="N1">
      <boxing_gloves_model>Спорт молдед</boxing_gloves_model>
      <boxing_gloves_price currency="лев">75.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>9</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="31" available_in_shop="N1">
      <boxing_gloves_model>Траин спорт</boxing_gloves_model>
      <boxing_gloves_price currency="лев">55.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="30" available_in_shop="N1">
      <shoes_model>Спорт стоп</shoes_model>
      <shoes_price currency="лев">84.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>сини</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="31" available_in_shop="N1">
      <shoes_model>Кевлер</shoes_model>
      <shoes_price currency="лев">94.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>зелени</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>
