=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT sport_shop ( shop_info, supplements, sport_accessories ) >

<!ELEMENT shop_info ( shop_name, country, city, address, phone, email, site) >
<!ATTLIST shop_info shop_id ID #REQUIRED>
<!ELEMENT shop_name ( #PCDATA ) >
<!ELEMENT country ( #PCDATA ) >
<!ELEMENT city ( #PCDATA ) >
<!ELEMENT address ( #PCDATA ) >
<!ELEMENT phone ( #PCDATA ) >
<!ELEMENT email ( #PCDATA ) >
<!ELEMENT site ( #PCDATA ) >

<!ELEMENT supplements ( supplement+ ) >
<!ELEMENT supplement (supplement_name, supplement_price, supplement_rating, taste,  packing, servings) >
<!ATTLIST supplement supplement_id CDATA #REQUIRED
			              type CDATA #REQUIRED		                                            
			              purpose CDATA #REQUIRED
			              supplement_brand CDATA #REQUIRED
			              available_in_shop  IDREFS #REQUIRED>
<!ELEMENT supplement_name ( #PCDATA ) >
<!ELEMENT supplement_price ( #PCDATA ) >
<!ATTLIST supplement_price currency CDATA #REQUIRED>
<!ELEMENT supplement_rating ( #PCDATA ) >
<!ELEMENT taste ( #PCDATA ) >
<!ELEMENT packing ( #PCDATA ) >
<!ATTLIST packing measurement_unit CDATA #REQUIRED >
<!ELEMENT servings ( #PCDATA ) >

<!ELEMENT sport_accessories (boxing_gloves+,  sport_shoes+) >

<!ELEMENT boxing_gloves ( boxing_gloves_model,boxing_gloves_price, boxing_gloves_size,  boxing_gloves_rating, boxing_gloves_material, origin) >
<!ATTLIST boxing_gloves boxing_gloves_id CDATA #REQUIRED
                                available_in_shop  IDREFS #REQUIRED>
<!ELEMENT boxing_gloves_model ( #PCDATA ) >
<!ELEMENT boxing_gloves_price ( #PCDATA ) >
<!ATTLIST  boxing_gloves_price currency CDATA #REQUIRED >
<!ELEMENT boxing_gloves_size ( #PCDATA ) >
<!ELEMENT boxing_gloves_rating ( #PCDATA ) >
<!ELEMENT boxing_gloves_material ( #PCDATA ) >
<!ELEMENT origin ( #PCDATA ) >

<!ELEMENT sport_shoes ( shoes_model, shoes_price, shoes_size, shoes_color, shoes_brand) >
<!ATTLIST sport_shoes sport_shoes_id CDATA #REQUIRED 
                                available_in_shop  IDREFS #REQUIRED>
<!ELEMENT shoes_model ( #PCDATA ) >
<!ELEMENT shoes_price ( #PCDATA ) >
<!ATTLIST shoes_price currency CDATA #REQUIRED >
<!ELEMENT shoes_size ( #PCDATA ) >
<!ELEMENT  shoes_color ( #PCDATA ) >
<!ELEMENT shoes_brand ( #PCDATA ) >

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="23"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Oптимум нутришън" available_in_shop="N1">
      <supplement_name>Нитро голд</supplement_name>
      <supplement_price currency="лев">102.00</supplement_price>
      <supplement_rating>9</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">2.225</packing>
      <servings>22 дози</servings>
    </supplement>
    <supplement supplement_id="24"  type="Гейнъри" purpose="Стимулира покачването на тегло"  supplement_brand="Универсал" available_in_shop="N1">
      <supplement_name>Ирон мас</supplement_name>
      <supplement_price currency="лев">78.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">5.000</packing>
      <servings>20 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="22" available_in_shop="N1">
      <boxing_gloves_model>Траин</boxing_gloves_model>
      <boxing_gloves_price currency="лев">65.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="23" available_in_shop="N1">
      <boxing_gloves_model>Аибаспорт</boxing_gloves_model>
      <boxing_gloves_price currency="лев">80.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>8</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="22" available_in_shop="N1">
      <shoes_model>Бловед</shoes_model>
      <shoes_price currency="лев">84.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="23" available_in_shop="N1">
      <shoes_model>Лите</shoes_model>
      <shoes_price currency="лев">94.00</shoes_price>
      <shoes_size>40</shoes_size>
      <shoes_color>сини</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-17.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="33" type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Амикс" available_in_shop="N1">
      <supplement_name>Креа трикс</supplement_name>
      <supplement_price currency="лев">53.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50 дози</servings>
    </supplement>
    <supplement supplement_id="34"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Мекс" available_in_shop="N1">
      <supplement_name>Протеин изолат</supplement_name>
      <supplement_price currency="лев">45.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>ванилия</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>10 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="32" available_in_shop="N1">
      <boxing_gloves_model>Спортисимо</boxing_gloves_model>
      <boxing_gloves_price currency="лев">75.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>9</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>СЗ</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="33" available_in_shop="N1">
      <boxing_gloves_model>Спортпро</boxing_gloves_model>
      <boxing_gloves_price currency="лев">45.00</boxing_gloves_price>
      <boxing_gloves_size>16 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>6</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Праид</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="32" available_in_shop="N1">
      <shoes_model>Сурго</shoes_model>
      <shoes_price currency="лев">54.00</shoes_price>
      <shoes_size>40</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="33" available_in_shop="N1">
      <shoes_model>Нарита</shoes_model>
      <shoes_price currency="лев">64.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="29"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Универсал" available_in_shop="N1">
      <supplement_name>Пауър</supplement_name>
      <supplement_price currency="лев">48.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>ванилия</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>10 дози</servings>
    </supplement>
    <supplement supplement_id="30"  type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Биотеч" available_in_shop="N1">
      <supplement_name>Креатестон</supplement_name>
      <supplement_price currency="лев">52.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="28" available_in_shop="N1">
      <boxing_gloves_model>Спидер</boxing_gloves_model>
      <boxing_gloves_price currency="лев">57.00</boxing_gloves_price>
      <boxing_gloves_size>14 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="29" available_in_shop="N1">
      <boxing_gloves_model>Протекс</boxing_gloves_model>
      <boxing_gloves_price currency="лев">56.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="28" available_in_shop="N1">
      <shoes_model>Канадия</shoes_model>
      <shoes_price currency="лев">74.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="29" available_in_shop="N1">
      <shoes_model>Проф</shoes_model>
      <shoes_price currency="лев">86.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="1"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Oптимум нутришън" available_in_shop="N1">
      <supplement_name>Голд Стандарт</supplement_name>
      <supplement_price currency="лев">102.00</supplement_price>
      <supplement_rating>9</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">2.225</packing>
      <servings>22</servings>
    </supplement>
    <supplement supplement_id="2"  type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Универсал" available_in_shop="N1">
      <supplement_name>Креатин монохидрат</supplement_name>
      <supplement_price currency="лев">58.00</supplement_price>
      <supplement_rating>9</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="1" available_in_shop="N1">
      <boxing_gloves_model>Ерго молдед</boxing_gloves_model>
      <boxing_gloves_price currency="лев">75.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>9</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="2" available_in_shop="N1">
      <boxing_gloves_model>Аиба</boxing_gloves_model>
      <boxing_gloves_price currency="лев">230.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>10</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="1" available_in_shop="N1">
      <shoes_model>Дурамо</shoes_model>
      <shoes_price currency="лев">84.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="2" available_in_shop="N1">
      <shoes_model>Фалкон</shoes_model>
      <shoes_price currency="лев">94.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>
