=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT sport_shop ( shop_info, supplements, sport_accessories ) >

<!ELEMENT shop_info ( shop_name, country, city, address, phone, email, site) >
<!ATTLIST shop_info shop_id ID #REQUIRED>
<!ELEMENT shop_name ( #PCDATA ) >
<!ELEMENT country ( #PCDATA ) >
<!ELEMENT city ( #PCDATA ) >
<!ELEMENT address ( #PCDATA ) >
<!ELEMENT phone ( #PCDATA ) >
<!ELEMENT email ( #PCDATA ) >
<!ELEMENT site ( #PCDATA ) >

<!ELEMENT supplements ( supplement+ ) >
<!ELEMENT supplement (supplement_name, supplement_price, supplement_rating, taste,  packing, servings) >
<!ATTLIST supplement supplement_id CDATA #REQUIRED
			              type CDATA #REQUIRED		                                            
			              purpose CDATA #REQUIRED
			              supplement_brand CDATA #REQUIRED
			              available_in_shop  IDREFS #REQUIRED>
<!ELEMENT supplement_name ( #PCDATA ) >
<!ELEMENT supplement_price ( #PCDATA ) >
<!ATTLIST supplement_price currency CDATA #REQUIRED>
<!ELEMENT supplement_rating ( #PCDATA ) >
<!ELEMENT taste ( #PCDATA ) >
<!ELEMENT packing ( #PCDATA ) >
<!ATTLIST packing measurement_unit CDATA #REQUIRED >
<!ELEMENT servings ( #PCDATA ) >

<!ELEMENT sport_accessories (boxing_gloves+,  sport_shoes+) >

<!ELEMENT boxing_gloves ( boxing_gloves_model,boxing_gloves_price, boxing_gloves_size,  boxing_gloves_rating, boxing_gloves_material, origin) >
<!ATTLIST boxing_gloves boxing_gloves_id CDATA #REQUIRED
                                available_in_shop  IDREFS #REQUIRED>
<!ELEMENT boxing_gloves_model ( #PCDATA ) >
<!ELEMENT boxing_gloves_price ( #PCDATA ) >
<!ATTLIST  boxing_gloves_price currency CDATA #REQUIRED >
<!ELEMENT boxing_gloves_size ( #PCDATA ) >
<!ELEMENT boxing_gloves_rating ( #PCDATA ) >
<!ELEMENT boxing_gloves_material ( #PCDATA ) >
<!ELEMENT origin ( #PCDATA ) >

<!ELEMENT sport_shoes ( shoes_model, shoes_price, shoes_size, shoes_color, shoes_brand) >
<!ATTLIST sport_shoes sport_shoes_id CDATA #REQUIRED 
                                available_in_shop  IDREFS #REQUIRED>
<!ELEMENT shoes_model ( #PCDATA ) >
<!ELEMENT shoes_price ( #PCDATA ) >
<!ATTLIST shoes_price currency CDATA #REQUIRED >
<!ELEMENT shoes_size ( #PCDATA ) >
<!ELEMENT  shoes_color ( #PCDATA ) >
<!ELEMENT shoes_brand ( #PCDATA ) >

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-06.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="11"  type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Биотеч" available_in_shop="N1">
      <supplement_name>Креатор</supplement_name>
      <supplement_price currency="лев">29.00</supplement_price>
      <supplement_rating>10</supplement_rating>
      <taste>портокал</taste>
      <packing measurement_unit="кг">0.300</packing>
      <servings>15 дози</servings>
    </supplement>
    <supplement supplement_id="12" type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Сцитец" available_in_shop="N1">
      <supplement_name>Креаформ</supplement_name>
      <supplement_price currency="лев">45.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">0.660</packing>
      <servings>33 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="11" available_in_shop="N1">
      <boxing_gloves_model>Топ</boxing_gloves_model>
      <boxing_gloves_price currency="лев">55.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>СЗ</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="12" available_in_shop="N1">
      <boxing_gloves_model>Оргин</boxing_gloves_model>
      <boxing_gloves_price currency="лев">66.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>8</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Адидас</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="11" available_in_shop="N1">
      <shoes_model>Елит</shoes_model>
      <shoes_price currency="лев">94.00</shoes_price>
      <shoes_size>46</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="12" available_in_shop="N1">
      <shoes_model>Ванака</shoes_model>
      <shoes_price currency="лев">86.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-08.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="15"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Oптимум нутришън" available_in_shop="N1">
      <supplement_name>Комплете</supplement_name>
      <supplement_price currency="лев">102.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">2.225</packing>
      <servings>22 дози</servings>
    </supplement>
    <supplement supplement_id="16"  type="Аминокиселини" purpose="Изгаряне на мазнини"  supplement_brand="Универсал" available_in_shop="N1">
      <supplement_name>Амино</supplement_name>
      <supplement_price currency="лев">41.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>30 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="15" available_in_shop="N1">
      <boxing_gloves_model>ББС</boxing_gloves_model>
      <boxing_gloves_price currency="лев">55.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="16" available_in_shop="N1">
      <boxing_gloves_model>Аибо</boxing_gloves_model>
      <boxing_gloves_price currency="лев">74.00</boxing_gloves_price>
      <boxing_gloves_size>14 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>8</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Адидас</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="15" available_in_shop="N1">
      <shoes_model>Епик</shoes_model>
      <shoes_price currency="лев">84.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>бяли</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="16" available_in_shop="N1">
      <shoes_model>Епик елит</shoes_model>
      <shoes_price currency="лев">94.00</shoes_price>
      <shoes_size>39</shoes_size>
      <shoes_color>сини</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-09.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="17"  type="Гейнъри" purpose="Стимулира покачването на тегло"  supplement_brand="Гаспари" available_in_shop="N1">
      <supplement_name>Гаин Про</supplement_name>
      <supplement_price currency="лев">85.00</supplement_price>
      <supplement_rating>6</supplement_rating>
      <taste>ванилия</taste>
      <packing measurement_unit="кг">1.800</packing>
      <servings>15 дози</servings>
    </supplement>
    <supplement supplement_id="18" type="Аминокиселини" purpose="Изгаряне на мазнини"  supplement_brand="Гаспари" available_in_shop="N1">
      <supplement_name>Амино Ласт</supplement_name>
      <supplement_price currency="лев">64.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">0.450</packing>
      <servings>22 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="17" available_in_shop="N1">
      <boxing_gloves_model>Фоам</boxing_gloves_model>
      <boxing_gloves_price currency="лев">55.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="17" available_in_shop="N1">
      <shoes_model>Род</shoes_model>
      <shoes_price currency="лев">58.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>бяли</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="18" available_in_shop="N1">
      <shoes_model>Екстра</shoes_model>
      <shoes_price currency="лев">106.00</shoes_price>
      <shoes_size>46</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-14.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="27"  type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Oптимум нутришън" available_in_shop="N1">
      <supplement_name>Мега Креатин</supplement_name>
      <supplement_price currency="лев">49.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>портокал</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50 дози</servings>
    </supplement>
    <supplement supplement_id="28"  type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Универсал" available_in_shop="N1">
      <supplement_name>Креатин монохидрат</supplement_name>
      <supplement_price currency="лев">48.00</supplement_price>
      <supplement_rating>9</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>50 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="26" available_in_shop="N1">
      <boxing_gloves_model>Проф</boxing_gloves_model>
      <boxing_gloves_price currency="лев">65.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>8</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Адидас</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="27" available_in_shop="N1">
      <boxing_gloves_model>Трен</boxing_gloves_model>
      <boxing_gloves_price currency="лев">48.00</boxing_gloves_price>
      <boxing_gloves_size>14 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="26" available_in_shop="N1">
      <shoes_model>Лите</shoes_model>
      <shoes_price currency="лев">45.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="27" available_in_shop="N1">
      <shoes_model>Кевлер</shoes_model>
      <shoes_price currency="лев">94.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="19"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Сцитец" available_in_shop="N1">
      <supplement_name>Милк Комплекс</supplement_name>
      <supplement_price currency="лев">121.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>ванилия</taste>
      <packing measurement_unit="кг">2.225</packing>
      <servings>22 дози</servings>
    </supplement>
    <supplement supplement_id="20" type="Гейнъри" purpose="Стимулира покачването на тегло"  supplement_brand="Биотеч" available_in_shop="N1">
      <supplement_name>Волумас</supplement_name>
      <supplement_price currency="лев">117.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">2.950</packing>
      <servings>15 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="18" available_in_shop="N1">
      <boxing_gloves_model>Протект</boxing_gloves_model>
      <boxing_gloves_price currency="лев">145.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>9</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Хаябушу</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="19" available_in_shop="N1">
      <boxing_gloves_model>Проф</boxing_gloves_model>
      <boxing_gloves_price currency="лев">56.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Праид</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="19" available_in_shop="N1">
      <shoes_model>Брезе</shoes_model>
      <shoes_price currency="лев">64.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="5"  type="Азотни бустери" purpose="Стимулиране на енергийните нива"  supplement_brand="БСН" available_in_shop="N1">
      <supplement_name>Джак3д</supplement_name>
      <supplement_price currency="лев">92.00</supplement_price>
      <supplement_rating>10</supplement_rating>
      <taste>портокал</taste>
      <packing measurement_unit="кг">0.145</packing>
      <servings>15 дози</servings>
    </supplement>
    <supplement supplement_id="6" type="Креатини" purpose="Увеличава издръжливостта"  supplement_brand="Сцитец" available_in_shop="N1">
      <supplement_name>Креа бомб</supplement_name>
      <supplement_price currency="лев">45.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">0.660</packing>
      <servings>33 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="5" available_in_shop="N1">
      <boxing_gloves_model>Родни</boxing_gloves_model>
      <boxing_gloves_price currency="лев">45.00</boxing_gloves_price>
      <boxing_gloves_size>14 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>6</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="6" available_in_shop="N1">
      <boxing_gloves_model>Латер</boxing_gloves_model>
      <boxing_gloves_price currency="лев">56.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Адидас</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="5" available_in_shop="N1">
      <shoes_model>Брезе</shoes_model>
      <shoes_price currency="лев">54.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>бяли</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="6" available_in_shop="N1">
      <shoes_model>Нарита</shoes_model>
      <shoes_price currency="лев">86.00</shoes_price>
      <shoes_size>42</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-07.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="13"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Алмакс" available_in_shop="N1">
      <supplement_name>Мускул Макс</supplement_name>
      <supplement_price currency="лев">28.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">0.450</packing>
      <servings>25 дози</servings>
    </supplement>
    <supplement supplement_id="14" type="Гейнъри" purpose="Стимулира покачването на тегло"  supplement_brand="Oптимум нутришън" available_in_shop="N1">
      <supplement_name>Хидро</supplement_name>
      <supplement_price currency="лев">81.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>шоколад</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>22 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="13" available_in_shop="N1">
      <boxing_gloves_model>Спорт</boxing_gloves_model>
      <boxing_gloves_price currency="лев">65.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>9</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Спортер</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="14" available_in_shop="N1">
      <boxing_gloves_model>Праид</boxing_gloves_model>
      <boxing_gloves_price currency="лев">58.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Спортер</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="13" available_in_shop="N1">
      <shoes_model>Спорт</shoes_model>
      <shoes_price currency="лев">64.00</shoes_price>
      <shoes_size>41</shoes_size>
      <shoes_color>бяли</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="14" available_in_shop="N1">
      <shoes_model>Респон</shoes_model>
      <shoes_price currency="лев">56.00</shoes_price>
      <shoes_size>40</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>

=== aleksandar-st/Homework/ASP.NET/AspProject/AspProject/App_Data/sport_shop-04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sport_shop SYSTEM "sport_shop.dtd">
<sport_shop>
  <shop_info shop_id="N1">
    <shop_name>Сила</shop_name>
    <country>България</country>
    <city>София</city>
    <address>Георги С. Раковски 176</address>
    <phone>0876142563</phone>
    <email>sila@gmail.com</email>
    <site>www.sila.com</site>
  </shop_info>
  <supplements>
    <supplement supplement_id="7"  type="Протеини" purpose="Изграждане на чисти мускули"  supplement_brand="Мекс" available_in_shop="N1">
      <supplement_name>Протеин изолат</supplement_name>
      <supplement_price currency="лев">114.00</supplement_price>
      <supplement_rating>8</supplement_rating>
      <taste>ванилия</taste>
      <packing measurement_unit="кг">2.225</packing>
      <servings>22 дози</servings>
    </supplement>
    <supplement supplement_id="8" type="Гейнъри" purpose="Стимулира покачването на тегло"  supplement_brand="Биотеч" available_in_shop="N1">
      <supplement_name>Хипер мас</supplement_name>
      <supplement_price currency="лев">38.00</supplement_price>
      <supplement_rating>7</supplement_rating>
      <taste>лимон</taste>
      <packing measurement_unit="кг">1.000</packing>
      <servings>10 дози</servings>
    </supplement>
  </supplements>
  <sport_accessories>
    <boxing_gloves boxing_gloves_id="7" available_in_shop="N1">
      <boxing_gloves_model>Канепки</boxing_gloves_model>
      <boxing_gloves_price currency="лев">279.00</boxing_gloves_price>
      <boxing_gloves_size>12 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>10</boxing_gloves_rating>
      <boxing_gloves_material>естествена кожа</boxing_gloves_material>
      <origin>Хаябушу</origin>
    </boxing_gloves>
    <boxing_gloves boxing_gloves_id="8" available_in_shop="N1">
      <boxing_gloves_model>ПВЦ</boxing_gloves_model>
      <boxing_gloves_price currency="лев">56.00</boxing_gloves_price>
      <boxing_gloves_size>10 ОЗ</boxing_gloves_size>
      <boxing_gloves_rating>7</boxing_gloves_rating>
      <boxing_gloves_material>изкуствена кожа</boxing_gloves_material>
      <origin>Еверласт</origin>
    </boxing_gloves>
    <sport_shoes sport_shoes_id="7" available_in_shop="N1">
      <shoes_model>Брезе</shoes_model>
      <shoes_price currency="лев">64.00</shoes_price>
      <shoes_size>44</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Адидас</shoes_brand>
    </sport_shoes>
    <sport_shoes sport_shoes_id="8" available_in_shop="N1">
      <shoes_model>Лите</shoes_model>
      <shoes_price currency="лев">76.00</shoes_price>
      <shoes_size>43</shoes_size>
      <shoes_color>черни</shoes_color>
      <shoes_brand>Пума</shoes_brand>
    </sport_shoes>
  </sport_accessories>
</sport_shop>
