=== aleksandar-st/Homework/XML/Homework-ShopNutritionSupplement/shop.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT shop ( supplements, types, purposes, packings_types ) >
	
    <!ELEMENT supplements ( supplement+ ) >
		<!ELEMENT supplement ( name, price, rating?, image?, quantity, taste, content, description, brand, packings ) >
			<!ATTLIST supplement 	id               ID            #REQUIRED
			                                            type 	   IDREFS  #REQUIRED
			                                            purpose  IDREFS  #REQUIRED >
            <!ELEMENT name ( #PCDATA ) >
            <!ELEMENT price ( #PCDATA ) >
            <!ELEMENT rating ( #PCDATA ) >
            <!ELEMENT image ( #PCDATA ) >
            <!ELEMENT quantity ( #PCDATA ) >
            <!ELEMENT taste ( #PCDATA ) >
            <!ELEMENT content ( material+ ) >
                <!ELEMENT material ( material_name, value, unit ) >
                    <!ELEMENT material_name ( #PCDATA ) >
	     <!ELEMENT value ( #PCDATA ) >
                    <!ELEMENT unit ( #PCDATA ) >
            <!ELEMENT description ( #PCDATA ) >
            <!ELEMENT brand ( #PCDATA ) >
            <!ELEMENT packings ( packing, measurement_unit, servings ) >
                <!ATTLIST packings packing_types_id IDREFS #REQUIRED >
                <!ELEMENT packing ( #PCDATA ) >
                <!ELEMENT measurement_unit ( #PCDATA ) >
                <!ELEMENT servings ( #PCDATA ) >

    <!ELEMENT types ( type+ ) >
        <!ELEMENT type ( #PCDATA ) >
            <!ATTLIST type type_id ID #REQUIRED >

    <!ELEMENT purposes ( purpose+ ) >
        <!ELEMENT purpose ( #PCDATA ) >
            <!ATTLIST purpose international_code ID	#REQUIRED >
            
    <!ELEMENT packings_types ( packing_types+ ) >
        <!ELEMENT packing_types ( #PCDATA ) >
            <!ATTLIST packing_types pid ID #REQUIRED >

=== aleksandar-st/Homework/XML/Homework-ShopNutritionSupplement/shop-5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shop SYSTEM "file:/C:/Users/user/Desktop/xml/shop.dtd">
<shop>
    <supplements>
        <supplement id="HR01021324" type="G" purpose="P06 G97">
            <name>Реал мас</name>
            <price>135.00</price>
            <rating>8</rating>
            <image>real_mass.jpg</image>
            <quantity>1</quantity>
            <taste>ягода</taste>
            <content>
                <material>
                    <material_name>протеин</material_name>
                    <value>100</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Реал мас съдържа висококачествени калории, за да ви помогне да изградите нова мускулна маса. Новата формула на Реал мас включва пробиотици, които помагат на протеина да се съхрани при производството и стомашните киселини, също така  помага за увеличаването на добрите бактерии във вашата храносмилателна система, както и за високото качество на калориите за РЕАЛЕН мускулен растеж.Реал мас е добър и в набавянето на калории, но добавянето на калории от качествени източници ви дава много по-добра полза и ефект, сравнено с калории от лоши източници. Реал мас е всичко от което имате нужда за правилно възтановяване  и покачване на мускулна маса, той съдържа всико което е неоходимо за  един наистина страхотен гейнър.
            </description>
            <brand>Гаспари</brand>
            <packings packing_types_id="P01">
                <packing>5.000</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>50 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR01036834" type="AK" purpose="P06 E37 K78">
            <name>Амино макс</name>
            <price>48.00</price>
            <image>amino_max.jpg</image>
            <quantity>1</quantity>
            <taste>портокал</taste>
            <content>
                <material>
                    <material_name>аминокиселини</material_name>
                    <value>20</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Тази уникална иновативна формула  предлага на запознатия потребител един много полезен и усвояем продукт, който набавя широк спектър от най-важните и ефективни градивни материали за растежа и поддържането на скелетната мускулна тъкан и маса. Хидролизираният протеин използван в Амино макс е богат на ди и трипептиди, които помагат за бързото усвояване и снабдяване на мускулите с необходимите вещества. Левцинът  е крайно необходима аминокиселина, което означава, че организмът не може сам да я произведе; затова тя трябва да се набави външно от хранителен източник или чрез диетична хранителна добавка, като Амино макс.
            </description>
            <brand>Гаспари</brand>
            <packings packing_types_id="P01">
                <packing>0.450</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>22 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR10789243" type="K" purpose="AK36 G97 K78">
            <name>Креа бомб</name>
            <price>45.00</price>
            <rating>10</rating>
            <image>crea_bomb.jpg</image>
            <quantity>1</quantity>
            <taste>лимон</taste>
            <content>
                <material>
                    <material_name>креатин</material_name>
                    <value>20</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Креа бомб ще зареди мускулните ти клетки с всяка по-значима версия на креатина. Тази формула включва някои от „двойно-действащите” креатинови компоненти, където креатина е химически свързан с други субстанции, които имат силни ергогенни свойства, т.е. подобряват значително издръжливостта и работоспособността.
            </description>
            <brand>Сцитец</brand>
            <packings packing_types_id="P01">
                <packing>0.660</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>33 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR31036214" type="K" purpose="AK36 K58 AB47">
            <name>Креатестон</name>
            <price>51.00</price>
            <rating>7</rating>
            <image>createston.jpg</image>
            <quantity>1</quantity>
            <taste>череша</taste>
            <content>
                <material>
                    <material_name>креатин</material_name>
                    <value>15</value>
                    <unit>г</unit>
                </material>
                <material>
                    <material_name>глутамин</material_name>
                    <value>5</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Креатестон е нашият евтин мускулен строител от типа всичко в едно, с много от познатите до момента ефективни хранителни вещества и изграждащисубстрати за максимална и естественасила, събрани в един продукт.За разлика от другите два варианта, Креатестон има по-високо съдържание на протеини и въглехидрати и не съдържа толкова много ергогеници (силови модулатори). Високото съдържание на въглехидрати означава, че можете да постигнете много висока ефективност - за тези спортисти, които не са предразположени към силно тяло (трудно, но нормално трупащи) или се намират извън диетната фаза и нямат ограничение върху приема на въглехидрати.
            </description>
            <brand>Биотеч</brand>
            <packings packing_types_id="Т02">
                <packing>60</packing>
                <measurement_unit>таб</measurement_unit>
                <servings>20 дози</servings>
            </packings>            
        </supplement>
        <supplement id="HR14530486" type="P" purpose="P06 AK36 AB47">
            <name>Пауър</name>
            <price>24.00</price>
            <rating>7</rating>
            <image>power.jpg</image>
            <quantity>1</quantity>
            <taste>ванилия</taste>
            <content>
                <material>
                    <material_name>протеин</material_name>
                    <value>50</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Пауър протеин е продуктът, от който се нуждае всеки сериозен атлет. Уникалната му формула гарантира големи резултати. Благодарение на балансираната комбинация от висококачествен протеин, витамини и минерали, Вие ще постигнете Вашите цели докато тренирате усърдно. Ефектът от използването на Пауър протеин е оценен в цял свят от множество атлети.
            </description>
            <brand>Универсал</brand>
            <packings packing_types_id="P01">
                <packing>0.454</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>10 дози</servings>
            </packings>
        </supplement>
    </supplements>
    <types>
        <type type_id="P">Протеини</type>
        <type type_id="AK">Аминокиселини</type>
        <type type_id="K">Креатини</type>
        <type type_id="VM">Витамини и минерали</type>
        <type type_id="G">Гейнъри</type>
        <type type_id="AB">Азотни бустери</type>
        <type type_id="E">Енергийни продукти</type>
    </types>
    <purposes>
        <purpose international_code="P06">Насърчава растежа на мускулна маса</purpose>
        <purpose international_code="AK36">Подобрява възстановяването</purpose>
        <purpose international_code="K58">Намалява умората</purpose>
        <purpose international_code="VM09">Нормализира кръвното налягане</purpose>
        <purpose international_code="G97">Покачване на мускулна маса</purpose>
        <purpose international_code="AB47">Прилив на чиста енергия</purpose>
        <purpose international_code="E37">Засилена концентрация</purpose>
        <purpose international_code="AB49">Увеличаване на  енергия и качване на мускулна маса</purpose>
        <purpose international_code="K78">Повишава енергията</purpose>
    </purposes>
    <packings_types>
        <packing_types pid="P01">прах</packing_types>
        <packing_types pid="Т02">таблетки</packing_types>
        <packing_types pid="F03">течност</packing_types>
    </packings_types>
</shop>

=== aleksandar-st/Homework/XML/Homework-ShopNutritionSupplement/shop-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shop SYSTEM "file:/C:/Users/user/Desktop/xml/shop.dtd">
<shop>
    <supplements>
        <supplement id="HR01021324" type="P" purpose="P21 VM74">
            <name>Голд Стандарт</name>
            <price>102.00</price>
            <rating>9</rating>
            <image>gold_standard.jpg</image>
            <quantity>1</quantity>
            <taste>шоколад</taste>
            <content>
                <material>
                    <material_name>протеин</material_name>
                    <value>100</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Голд Стандарте бил най-продаваната хранителна добавка в културизма. Това е продукт за тези, които се опитват да покачат чиста мускулна маса! Изолат на суроватъчен протеин се състои от чист протеин, а тази протеинова добавка няма високо съдържание на мазнини, лактоза и холестерол, както други протеинови добавки обикновено обичат да пазят в тайна. Oптимум нутришън е марка известна с налагане на стандарт за протеинови добавки и това може да е причината, поради която те могат да наименоват този продукт директно като златният стандарт за суроватъчен протеин. Много други протеинови добавки се опитват направят подобни твърдения, но ако изследвате ключовите съставки на други "чисти" суроватъчни протеини на пазара, ще откриете, че тези продукти са пълни с изкуствени подсладители, химикали, цветови и различни вкусови подобрители.
            </description>
            <brand>Oптимум нутришън</brand>
            <packings packing_types_id="P01">
                <packing>2.225</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>22 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR01036834" type="AK" purpose="AK54 K04">
            <name>Амино х</name>
            <price>41.00</price>
            <rating>8</rating>
            <image>amino_x.jpg</image>
            <quantity>1</quantity>
            <taste>ябълка</taste>
            <content>
                <material>
                    <material_name>аминокиселини</material_name>
                    <value>10</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>Амино х е първият ефервесцентен продукт за издръжливост и възстановяване. Предназначен е за подпомагане на протеиновия синтез, ресинтез на гликоген, съхраняване на мускулите, въстановяване от тежки тренировки, мускулна издръжливост и устойчивост на мускулна умора.</description>
            <brand>БСН</brand>
            <packings packing_types_id="P01">
                <packing>0.300</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>30 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR10789243" type="K" purpose="K4">
            <name>Креатин монохидрат</name>
            <price>45.00</price>
            <rating>10</rating>
            <image>creatine_monohydrate.jpg</image>
            <quantity>1</quantity>
            <taste>портокал</taste>
            <content>
                <material>
                    <material_name>креатин</material_name>
                    <value>20</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Креатин монохидрат е готов източник на енергия за мускулите. Превръща се несъмнено в един от най-добрите продукти за повишаване на мускулната сила. Освен подсилване на мускулите и увеличаване на мускулната маса,  креатин монохидрат има енергизиращо действие и върху останалите части на тялото. Креатинът е био-молекула, която произвежда АТФ. Той е продукт, синтезиран в човешкото тяло, който се произвежда от черния дроб и се складира в мозъка, скелетната и сърдечна мускулатура и който служи като готов източник за производство на АТФ. Креатинът е ключово вещество, подпомагащо ускорено презареждане на АТФ в мускулите. По-голямо количество от него води до увеличено производство на енергия, което позволява на мускулите да работят по-дълго и при по-висока интензивност. Креатинът е повече от ергогенен хранителен елемент: той има уголемяващ ефект върху мускулите. Клетъчното увеличение или клетъчната хидратация включва свързване на водата с мускулните фибри. Тази връзка придава „напомпан” вид. Тъй като водата е свързана вътре в мускула, атлетите, използващи креатин, нямат „подпухнала” външност. С други думи, мускулите изглеждат по-големи, а същевременно се характеризират с повишена сила, енергия и издръжливост. Това им позволява да се възстановяват по-бързо и да разполагат с повече енергия за всяка тренировъчна сесия.
            </description>
            <brand>Ултимейт</brand>
            <packings packing_types_id="P01">
                <packing>1.000</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>50 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR31036214" type="K" purpose="K4">
            <name>Креатор</name>
            <price>29.00</price>
            <rating>7</rating>
            <image>creator.jpg</image>
            <quantity>1</quantity>
            <taste>ябълка</taste>
            <content>
                <material>
                    <material_name>креатин</material_name>
                    <value>10</value>
                    <unit>г</unit>
                </material>
                <material>
                    <material_name>глутамин</material_name>
                    <value>2</value>
                    <unit>г</unit>
                </material>
                <material>
                    <material_name>калциум</material_name>
                    <value>3</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>Креатор е единствен в света на хранителните добавки. Това е алкализиран креатин с увеличен пхц нива усвояване и ефективност, които задминават далеч тези на другите креатинови съставки. Креатор съдържа Микронизиран креатин, най-чистата креатинова монохидратна съставка, която е достъпна. Разтваря се бързо и напълно все едно е обработен до изключително фини 180 микрона. Благодарение на невероятната степен на разтворимост, той навлиза в кръвообращението и мускулите в 90% форма на готовност за ползване. </description>
            <brand>Биотеч</brand>
            <packings packing_types_id="Т02">
                <packing>40</packing>
                <measurement_unit>таб</measurement_unit>
                <servings>20 дози</servings>
            </packings>            
        </supplement>
        <supplement id="HR14530486" type="P" purpose="P21 VM74">
            <name>Предатор</name>
            <price>52.00</price>
            <rating>6</rating>
            <image>predator.jpg</image>
            <quantity>1</quantity>
            <taste>ванилия</taste>
            <content>
                <material>
                    <material_name>протеин</material_name>
                    <value>100</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>Предатор представлява изключително качествен суроватъчен протеин концентрат, специално създаден под формата на добавка към високопротеинов хранителен режим. Тази формула е основно насочена към атлети, културисти и професионални спортисти, нуждаещи се от всекидневен голям протеинов прием за изграждане на мускулна тъкан,  увеличаване на силата и поддържане на регенерацията след изтощителна тренировка.Предатор доставя изграждащите структури за бърз растеж на чиста мускулатура, поддържа възстановяването след тренировъчни сесии и притежава отличен, мек вкус! Той съдържа ултра-филтриран, обработен при ниска температура и незабавно разтворим суроватъчен протеин концентрат, както и високо количество аминокиселини, извлечени от говежди протеин.</description>
            <brand>Амикс</brand>
            <packings packing_types_id="P01">
                <packing>2.250</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>22 дози</servings>
            </packings> 
        </supplement>
    </supplements>
    <types>
        <type type_id="P">Протеини</type>
        <type type_id="AK">Аминокиселини</type>
        <type type_id="K">Креатини</type>
        <type type_id="VM">Витамини и минерали</type>
        <type type_id="G">Гейнъри</type>
        <type type_id="AB">Азотни бустери</type>
        <type type_id="E">Енергийни продукти</type>
    </types>
    <purposes>
        <purpose international_code="P21">Качване на чиста мускулна маса</purpose>
        <purpose international_code="AK54">Въстановяване от тежки тренировки</purpose>
        <purpose international_code="K4">Увеличаване на енергия и сила</purpose>
        <purpose international_code="VM74">Приемане на необходимите за деня хранителни вещества</purpose>
        <purpose international_code="G34">Качване на мускулна маса</purpose>
        <purpose international_code="AB35">Мускулната издържливост, сила и предотвратяване на мускулната умора, мускулен растеж, активна умствена дейност и концентрация</purpose>
        <purpose international_code="E67">Увеличаване на  васкуларността и напомпването</purpose>
        <purpose international_code="AB51">Увеличаване на  енергия и качване на мускулна маса</purpose>
        <purpose international_code="K04">Мускулната издържливост</purpose>
    </purposes>
    <packings_types>
        <packing_types pid="P01">прах</packing_types>
        <packing_types pid="Т02">таблетки</packing_types>
        <packing_types pid="F03">течност</packing_types>
    </packings_types>
</shop>
