=== aleksandar-st/Homework/XML/Homework-ShopNutritionSupplement/shop.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT shop ( supplements, types, purposes, packings_types ) >
	
    <!ELEMENT supplements ( supplement+ ) >
		<!ELEMENT supplement ( name, price, rating?, image?, quantity, taste, content, description, brand, packings ) >
			<!ATTLIST supplement 	id               ID            #REQUIRED
			                                            type 	   IDREFS  #REQUIRED
			                                            purpose  IDREFS  #REQUIRED >
            <!ELEMENT name ( #PCDATA ) >
            <!ELEMENT price ( #PCDATA ) >
            <!ELEMENT rating ( #PCDATA ) >
            <!ELEMENT image ( #PCDATA ) >
            <!ELEMENT quantity ( #PCDATA ) >
            <!ELEMENT taste ( #PCDATA ) >
            <!ELEMENT content ( material+ ) >
                <!ELEMENT material ( material_name, value, unit ) >
                    <!ELEMENT material_name ( #PCDATA ) >
	     <!ELEMENT value ( #PCDATA ) >
                    <!ELEMENT unit ( #PCDATA ) >
            <!ELEMENT description ( #PCDATA ) >
            <!ELEMENT brand ( #PCDATA ) >
            <!ELEMENT packings ( packing, measurement_unit, servings ) >
                <!ATTLIST packings packing_types_id IDREFS #REQUIRED >
                <!ELEMENT packing ( #PCDATA ) >
                <!ELEMENT measurement_unit ( #PCDATA ) >
                <!ELEMENT servings ( #PCDATA ) >

    <!ELEMENT types ( type+ ) >
        <!ELEMENT type ( #PCDATA ) >
            <!ATTLIST type type_id ID #REQUIRED >

    <!ELEMENT purposes ( purpose+ ) >
        <!ELEMENT purpose ( #PCDATA ) >
            <!ATTLIST purpose international_code ID	#REQUIRED >
            
    <!ELEMENT packings_types ( packing_types+ ) >
        <!ELEMENT packing_types ( #PCDATA ) >
            <!ATTLIST packing_types pid ID #REQUIRED >

=== aleksandar-st/Homework/XML/Homework-ShopNutritionSupplement/shop-x-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shop SYSTEM "file:/C:/Users/user/Desktop/xml/shop.dtd">
<shop>
    <supplements>
        <supplement id="HR69874512" type="P" purpose="P34 V47">
            <name>Нитро голд</name>
            <price>50.00</price>
            <rating>8</rating>
            <image>нитро.jpg</image>
            <quantity>1</quantity>
            <taste>кокос</taste>
            <content>
                <material>
                    <material-name>протеин</material-name>
                    <value>50</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Нитро голд съдържа , протеинова смес с 8 от най-добрите източници на протеини, които стимулират растежа и поддържането на мускулна маса. Нитро голд съдържа новата , специална комбинация от протеолитични ензими и пробиотици за улеснено храносмилане и усвояване.
            </description>
            <brand>Биотеч</brand>
            <packings packing_types_id="P01">
                <packing>0.500</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>10 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR436987456" type="G" purpose="P34 KR24">
            <name>Ирон мас</name>
            <price>111.00</price>
            <rating>10</rating>
            <image>iron_mass.jpg</image>
            <quantity>1</quantity>
            <taste>щоколад</taste>
            <content>
                <material>
                    <material_name>протеин</material_name>
                    <value>80</value>
                    <unit>г</unit>
                </material>
                <material>
                    <material_name>аминокиселини</material_name>
                    <value>20</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Ирон мас от серията Арнолд  е интелигентният начин да предизвикаш интензивен мускулен растеж, без това да доведе до натрупване на мазнини в тялото. Новата протеинова формула залага на висококачествената комбинация от хидролизиран телешки протеин,  аминокиселини.
            </description>
            <brand>Арнолд</brand>
            <packings packing_types_id="P01">
                <packing>1.000</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>10 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR45684921" type="P" purpose="P34 EN32">
            <name>Изофлекс</name>
            <price>107.00</price>
            <rating>10</rating>
            <image>isoflex.jpg</image>
            <quantity>1</quantity>
            <taste>ягода</taste>
            <content>
                <material>
                    <material_name>протеин</material_name>
                    <value>50</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Изофлекс съчетава четири патентовани системи за усвояване. Съставките във всяка система работят в синхрон, за да се осигури висококачество и отличен вкус.
            </description>
            <brand>Биотеч</brand>
            <packings packing_types_id="P01">
                <packing>1.000</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>20 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR87459621" type="VM" purpose="V47">
            <name>Витамин Ц</name>
            <price>25.00</price>
            <rating>6</rating>
            <image>vitaminC.jpg</image>
            <quantity>1</quantity>
            <taste>лимон</taste>
            <content>
                <material>
                    <material_name>витамин Ц</material_name>
                    <value>20</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Витамин С играе важна роля в жизнените процеси на организма като универсален активатор на клетъчния метаболизъм. Човешкият организъм не може да синтезира Витамин С и затова трябва да си го доставя чрез храната отвън. Витамин С подпомага възстановителните и защитни процеси в организма. Влияе благоприятно на функциите на централната нервна система, стимулира дейността на ендокринните жлези, подобрява усвояването на калция и желязото и нормалното кръвообразуване, подпомага профилактиката на различни видове вирусни и бактериални инфекции и участва в поддържането на здрава имунна система.
           </description>
            <brand>Биотеч</brand>
            <packings packing_types_id="Т02">
                <packing>50</packing>
                <measurement_unit>таб</measurement_unit>
                <servings>25 дози</servings>
            </packings>            
        </supplement>
        <supplement id="HR87459635" type="K" purpose="KR24">
            <name>Креатин транспорт</name>
            <price>38.00</price>
            <rating>7</rating>
            <image>creatine_transport.jpg</image>
            <quantity>1</quantity>
            <taste>лимон</taste>
            <content>
                <material>
                    <material_name>креатин хидрохлорид</material_name>
                    <value>15</value>
                    <unit>г</unit>
                </material>
                <material>
                    <material_name>калциум</material_name>
                    <value>5</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Креатинът  е важен, защото дава енергия за бързи мускулни движения, тъй като участва в синтеза на главния енергоносител - АТФ. Когато Креатин транспорт се приема с прости въглехидрати, той се усвоява много по-бързо. Поради тази причина в състава на продукта са включени и рибоза, декстроза и малтодекстрин. Присъства и комбинация от аминокиселини, витамини, минерали и антиоксиданти.            
            </description>
            <packings packing_types_id="P01">
                <packing>0.600</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>30 дози</servings>
            </packings>  
        </supplement>
    </supplements>
    <types>
        <type type_id="P">Протеини</type>
        <type type_id="AK">Аминокиселини</type>
        <type type_id="K">Креатини</type>
        <type type_id="VM">Витамини и минерали</type>
        <type type_id="G">Гейнъри</type>
        <type type_id="AB">Азотни бустери</type>
        <type type_id="E">Енергийни продукти</type>
    </types>
    <purposes>
        <purpose international_code="P34">Увеличава мускулния обем</purpose>
        <purpose international_code="A78">Подобрява производителността и високата интензивност на тренировката</purpose>
        <purpose international_code="KR24">Увеличава мускулната маса, силата и размерите</purpose>
        <purpose international_code="V47">Намалява мускулните болки</purpose>
        <purpose international_code="EN32">Производство на азотен оксид, напомпване на мускулите</purpose>
    </purposes>
    <packings_types>
        <packing_types pid="P01">прах</packing_types>
        <packing_types pid="Т02">таблетки</packing_types>
        <packing_types pid="F03">течност</packing_types>
    </packings_types>
</shop>

=== aleksandar-st/Homework/XML/Homework-ShopNutritionSupplement/shop-x-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shop SYSTEM "file:/C:/Users/user/Desktop/xml/shop.dtd">
<shop>
    <supplements>
        <supplement id="HR15698745" type="G" purpose="P51 VM097">
            <name>Маркед мас</name>
            <price>57.00</price>
            <rating>6</rating>
            <image>marked_mass.jpg</image>
            <quantity>1</quantity>
            <taste>ягода</taste>
            <content>
                <material>
                    <material_name>протеин</material_name>
                    <value>100</value>
                    <unit>г</unit>
                </material>
            </content>
            <brand>ГНЦ</brand>
            <packings packing_types_id="P01">
                <packing>1.135</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>10 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR62478984" type="AK" purpose="P51">
            <name>Аминос</name>
            <price>67.00</price>
            <rating>8</rating>
            <image>aminos.jpg</image>
            <quantity>1</quantity>
            <taste>лимон</taste>
            <content>
                <material>
                    <material_name>калциум</material_name>
                    <value>10</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Суроватъчните аминокиселини директно захранват тялото с необходимото количество аминокиселини. Aко се използва определено количество аминокиселини в комбинация с тежка тренировка, пептидите се използват за изграждане на мускула, а не се складират под формата на мазнини (протеинов синтез). Основният протеин в Суроватъчните Аминокиселини е биологично висококачествен суроватъчен протеин. Той се разгражда оптимално и аминокиселините могат бързо да се усвоят от мускулитеОписание на продукт.
            </description>
            <brand>Гаспари</brand>
            <packings packing_types_id="P01">
                <packing>60</packing>
                <measurement_unit>таб</measurement_unit>
                <servings>30 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR98745632" type="K" purpose="AB79 AK09">
            <name>Креа конг</name>
            <price>38.00</price>
            <rating>8</rating>
            <image>creakong.jpg</image>
            <quantity>1</quantity>
            <taste>портокал</taste>
            <content>
                <material>
                    <material_name>креатин</material_name>
                    <value>20</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Креатин монохидрат е готов източник на енергия за мускулите. Превръща се несъмнено в един от най-добрите продукти за повишаване на мускулната сила. Освен подсилване на мускулите и увеличаване на мускулната маса,  креатин монохидрат има енергизиращо действие и върху останалите части на тялото. Креатинът е био-молекула, която произвежда АТФ. Той е продукт, синтезиран в човешкото тяло, който се произвежда от черния дроб и се складира в мозъка, скелетната и сърдечна мускулатура и който служи като готов източник за производство на АТФ. Креатинът е ключово вещество, подпомагащо ускорено презареждане на АТФ в мускулите. По-голямо количество от него води до увеличено производство на енергия, което позволява на мускулите да работят по-дълго и при по-висока интензивност. Креатинът е повече от ергогенен хранителен елемент: той има уголемяващ ефект върху мускулите. Клетъчното увеличение или клетъчната хидратация включва свързване на водата с мускулните фибри. Тази връзка придава „напомпан” вид. Тъй като водата е свързана вътре в мускула, атлетите, използващи креатин, нямат „подпухнала” външност. С други думи, мускулите изглеждат по-големи, а същевременно се характеризират с повишена сила, енергия и издръжливост. Това им позволява да се възстановяват по-бързо и да разполагат с повече енергия за всяка тренировъчна сесия.
            </description>
            <brand>Мутант</brand>
            <packings packing_types_id="P01">
                <packing>0.500</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>25 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR348269175" type="K" purpose="AK09 AB24">
            <name>Тотал кратин</name>
            <price>29.00</price>
            <rating>6</rating>
            <image>total.jpg</image>
            <quantity>1</quantity>
            <taste>череша</taste>
            <content>
                <material>
                    <material_name>таурин</material_name>
                    <value>15</value>
                    <unit>г</unit>
                </material>
                <material>
                    <material_name>глутамин</material_name>
                    <value>5</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Креатин монохидрат е готов източник на енергия за мускулите. Превръща се несъмнено в един от най-добрите продукти за повишаване на мускулната сила. Освен подсилване на мускулите и увеличаване на мускулната маса,  креатин монохидрат има енергизиращо действие и върху останалите части на тялото. Креатинът е био-молекула, която произвежда АТФ. Той е продукт, синтезиран в човешкото тяло, който се произвежда от черния дроб и се складира в мозъка, скелетната и сърдечна мускулатура и който служи като готов източник за производство на АТФ. Креатинът е ключово вещество, подпомагащо ускорено презареждане на АТФ в мускулите. По-голямо количество от него води до увеличено производство на енергия, което позволява на мускулите да работят по-дълго и при по-висока интензивност. Креатинът е повече от ергогенен хранителен елемент: той има уголемяващ ефект върху мускулите. Клетъчното увеличение или клетъчната хидратация включва свързване на водата с мускулните фибри. Тази връзка придава „напомпан” вид. Тъй като водата е свързана вътре в мускула, атлетите, използващи креатин, нямат „подпухнала” външност. С други думи, мускулите изглеждат по-големи, а същевременно се характеризират с повишена сила, енергия и издръжливост. Това им позволява да се възстановяват по-бързо и да разполагат с повече енергия за всяка тренировъчна сесия.
            </description>
            <brand>Биотеч</brand>
            <packings packing_types_id="Т02">
                <packing>60</packing>
                <measurement_unit>таб</measurement_unit>
                <servings>30 дози</servings>
            </packings>            
        </supplement>
        <supplement id="HR14530486" type="P" purpose="AK09 K98">
            <name>Мулти протеин</name>
            <price>69.00</price>
            <rating>6</rating>
            <image>multi.jpg</image>
            <quantity>1</quantity>
            <taste>банан</taste>
            <content>
                <material>
                    <material_name>витамин Е</material_name>
                    <value>10</value>
                    <unit>г</unit>
                </material>
                <material>
                    <material_name>витамин Ц</material_name>
                    <value>10</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Мулти протеинот комбинира четири различни протеинови източника  в един разнообразен продукт. Казеинът, най-големият протеинов източник , е бавнодействащ протеин, който се абсорбира в тялото за продължителен период от време. Това не само дава на тялото продължителен източник на аминокиселини, но и създава дълготрайно усещане за заситеност. Уникалният състав е допълнен от суроватков протеин, яйчен албумин и глутаминови пептиди. Суроватката е бързодействащ протеинов източник, който поддържа имунната система и дава на тялото тъканно изграждащ заряд аминокиселини. 
            </description>
            <brand>Универсал</brand>
            <packings packing_types_id="P01">
                <packing>1.000</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>50 дози</servings>
            </packings>
        </supplement>
    </supplements>
    <types>
        <type type_id="P">Протеини</type>
        <type type_id="AK">Аминокиселини</type>
        <type type_id="K">Креатини</type>
        <type type_id="VM">Витамини и минерали</type>
        <type type_id="G">Гейнъри</type>
        <type type_id="AB">Азотни бустери</type>
        <type type_id="E">Енергийни продукти</type>
    </types>
    <purposes>
        <purpose international-code="P51">Потиска мускулната умора</purpose>
        <purpose international-code="AK09">Подобрява възстановяването</purpose>
        <purpose international_code="K98">Предпазване от загуба на мускулна маса</purpose>
        <purpose international_code="VM097">Поддържка на киселинния баланс в организма</purpose>
        <purpose international_code="AB24">Подобрява физическата активност</purpose>
        <purpose international_code="AB79">Бързо възстановяване след тренировка</purpose>
        <purpose international_code="K48">Повишава енергията</purpose>
    </purposes>
    <packings_types>
        <packing_types pid="P01">прах</packing_types>
        <packing_types pid="Т02">таблетки</packing_types>
        <packing_types pid="F03">течност</packing_types>
    </packings_types>
</shop>

=== aleksandar-st/Homework/XML/Homework-ShopNutritionSupplement/shop-js.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shop SYSTEM "file:/C:/Users/user/Desktop/xml/shop.dtd">
<shop><supplements><supplement id="HR01021324" type="P" purpose="P21"><name>Ð¨Ð¾Ðº</name><price>83</price><rating>5</rating><image>shock.jpg</image><quantity>1</quantity><taste>ÑˆÐ¾ÐºÐ¾Ð»Ð°Ð´</taste><content><material><material_name>Ð¿Ñ€Ð¾Ñ‚ÐµÐ¸Ð½</material_name><value>100</value><unit>Ð³</unit></material></content><description>ÐÐºÐ¾ Ð¸ÑÐºÐ°Ñ‚Ðµ Ð´Ð° ÑÑ‚Ðµ Ð·Ð°Ñ€ÐµÐ´ÐµÐ½Ð¸ Ð¸ Ð¼Ð¾Ñ‚Ð¸Ð²Ð¸Ñ€Ð°Ð½Ð¸ Ð²ÑŠÐ² Ñ„Ð¸Ñ‚Ð½ÐµÑÐ°, Ð¨Ð¾Ðº Ðµ Ñ‚Ð¾Ñ‡Ð½Ð¾ Ð·Ð° Ð²Ð°Ñ. Ð¢Ð°Ð·Ð¸ Ñ„Ð¾Ñ€Ð¼ÑƒÐ»Ð° Ñ‰Ðµ ÑÑ€Ð°Ð±Ð¾Ñ‚Ð¸ Ð¿Ñ€Ð¸ Ð½ÑÐºÐ¾Ð¸ Ð¼Ð½Ð¾Ð³Ð¾ Ð¸Ð½Ñ‚ÐµÐ½Ð·Ð¸Ð²Ð½Ð¸ Ñ‚Ñ€ÐµÐ½Ð¸Ñ€Ð¾Ð²ÐºÐ¸ Ð¸ Ñ‰Ðµ Ð²Ð¸ Ð¿Ð¾Ð¼Ð¾Ð³Ð½Ðµ Ð´Ð° Ð½Ð°Ñ‚Ñ€ÑƒÐ¿Ð°Ñ‚Ðµ Ð¼Ð°ÑÐ°. Ð¢ÑÐ»Ð¾Ñ‚Ð¾ Ð²Ð¸ Ñ‰Ðµ ÑÐµ Ñ‡ÑƒÐ²ÑÑ‚Ð²Ð° Ð·Ð°Ñ€ÐµÐ´ÐµÐ½Ð¾ Ð¿Ñ€ÐµÐ· Ñ†ÐµÐ»Ð¸Ñ Ð´ÐµÐ½ Ð¾Ñ‚ ÐºÑ€ÑŠÐ²Ñ‚Ð°, Ð²Ñ€ÑŠÑ…Ð»Ð¸Ñ‚Ð°Ñ‰Ð° Ð¼ÑƒÑÐºÑƒÐ»Ð½Ð°Ñ‚Ð° Ð²Ð¸ Ñ‚ÑŠÐºÐ°Ð½ Ð¸ Ð´Ð¾ÑÑ‚Ð°Ð²ÑÐ¹ÐºÐ¸ Ð½ÑƒÑ‚Ñ€Ð¸ÐµÐ½Ñ‚Ð¸Ñ‚Ðµ, Ð½ÐµÐ¾Ð±Ñ…Ð¾Ð´Ð¸Ð¼Ð¸ Ð·Ð° Ð¸ÑÑ‚Ð¸Ð½ÑÐºÐ¸ Ñ€Ð°ÑÑ‚ÐµÐ¶.</description><brand>Ð£Ð½Ð¸Ð²ÐµÑ€ÑÐ°Ð»</brand><packings packing_types_id="P01"><packing>2.225</packing><measurement_unit>ÐºÐ³</measurement_unit><servings>22 Ð´Ð¾Ð·Ð¸</servings></packings></supplement></supplements><types><type type_id="P">ÐŸÑ€Ð¾Ñ‚ÐµÐ¸Ð½Ð¸</type></types><purposes><purpose international_code="P21">Ð˜Ð·Ð³Ñ€Ð°Ð¶Ð´Ð°Ð½Ðµ Ð½Ð° Ñ‡Ð¸ÑÑ‚Ð¸ Ð¼ÑƒÑÐºÑƒÐ»Ð¸</purpose></purposes><packings_types><packing_types pid="P01">Ð¿Ñ€Ð°Ñ…</packing_types></packings_types></shop>

=== aleksandar-st/Homework/XML/Homework-ShopNutritionSupplement/shop-4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shop SYSTEM "file:/C:/Users/user/Desktop/xml/shop.dtd">
<shop>
    <supplements>
        <supplement id="HR40012841" type="P" purpose="P75 VM90 G60 E10 K99">
            <name>Протеин изолат</name>
            <price>114.00</price>
            <rating>8</rating>
            <image>isolate.jpg</image>
            <quantity>1</quantity>
            <taste>ванилия</taste>
            <content>
                <material>
                    <material_name>протеин</material_name>
                    <value>100</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Протеин изолат е една перфектната добавка към тренировъчен режим за сила и издръжливост. Всеки грам съдържа повече протеин и по-малко мазнини и въглехидрати от който и да било друг суроватъчен продукт. Протеин изолат е супер качествен суроватъчен протеин с перфектна усвояемост.
            </description>
            <brand>Мех</brand>
            <packings packing_types_id="P01">
                <packing>2.225</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>22 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR48698715" type="G" purpose="P75 AK40">
            <name>Хипер мас</name>
            <price>24.00</price>
            <rating>6</rating>
            <image>hyper_mass.jpg</image>
            <quantity>1</quantity>
            <taste>шоколад</taste>
            <content>
                <material>
                    <material_name>въглехидрати</material_name>
                    <value>100</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Хипер мас е идеалното решение за начинаещи спортисти, които биха искали да прибавят към дневната си диета допълнителни калории и протеини, за да увеличат чистата си мускулна маса. Хипер мас  увеличава силата на мускулите и обема на клетката до максималните и размери.
            </description>
            <brand>Биотеч</brand>
            <packings packing_types_id="P01">
                <packing>1.000</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>10 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR74586921" type="AB" purpose="AK40 G60 AB20">
            <name>Джак3д</name>
            <price>92.00</price>
            <rating>10</rating>
            <image>jack3d.jpg</image>
            <quantity>1</quantity>
            <taste>портокал</taste>
            <content>
                <material>
                    <material_name>аргинин нитрат</material_name>
                    <value>10</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Най-ексклузивните съставки с конкретни цели, за да донесат максимални резултати при минимално дозиране. Тази технология на съставките предлага истински мощен удар!Тренирайте, както не сте тренирали преди!С Джак3д тялото Ви се подпалва от най-свирепата и безмилостна тренировка, като след това мускулите Ви са напомпани и толкова заредени, че дори няма да повярвате!
            </description>
            <brand>УСП</brand>
            <packings packing_types_id="P01">
                <packing>0.145</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>15 дози</servings>
            </packings>
        </supplement>
        <supplement id="HR76984895" type="VM" purpose="P75 K50 VM90 E10 K99">
            <name>Опти мен</name>
            <price>56.00</price>
            <rating>6</rating>
            <image>opti_men.jpg</image>
            <quantity>1</quantity>
            <taste>портокал</taste>
            <content>
                <material>
                    <material_name>витамин Д</material_name>
                    <value>4</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Витамините и минералите, заедно с другите жизнено-важни хранителни вещества, са незаменими градивни елементи в човешкия организъм. Освен тяхната основополагаща роля, те отговарят и за енергийните нива, жизнеността и издръжливостта на тялото. Опти мен представлява цялостна система за усвояване на хранителните вещества.
            </description>
            <brand>Oптимум нутришън</brand>
            <packings packing_types_id="Т02">
                <packing>180</packing>
                <measurement_unit>таб</measurement_unit>
                <servings>30 дози</servings>
            </packings>            
        </supplement>
        <supplement id="HR78423641" type="K" purpose="K50">
            <name>Креа трикс</name>
            <price>53.00</price>
            <image>crea_trix.jpg</image>
            <quantity>1</quantity>
            <taste>лимон</taste>
            <content>
                <material>
                    <material_name>креатин хидрохлорид</material_name>
                    <value>20</value>
                    <unit>г</unit>
                </material>
            </content>
            <description>
                Използвайки креатин комплекса Креа трикс, тялото ви ще натрупва дори повече енергия, която ще се съхранява в мускулите Ви. Ще изпитате и увеличена сила и издръжливост. Сравнен със стандартния креатин, креатин комплекса Креа трикс може да гарантира на тялото ви по-бързи резултати. Формулата подпомага и по-лесната преработка на въглехидратите, така че да не се налага да се тревожите за стомашни болки или подуване, когато приемате тази добавка. В случай, че искате да натрупате по-големи мускули по най-бързия и естествен възможен начин, Креа трикс е именно добавката, която отговаря на нуждите ви.
            </description>
            <brand>Амикс</brand>
            <packings packing_types_id="P01">
                <packing>0.824</packing>
                <measurement_unit>кг</measurement_unit>
                <servings>40 дози</servings>
            </packings> 
        </supplement>
    </supplements>
    <types>
        <type type_id="P">Протеини</type>
        <type type_id="AK">Аминокиселини</type>
        <type type_id="K">Креатини</type>
        <type type_id="VM">Витамини и минерали</type>
        <type type_id="G">Гейнъри</type>
        <type type_id="AB">Азотни бустери</type>
        <type type_id="E">Енергийни продукти</type>
    </types>
    <purposes>
        <purpose international_code="P75">Изгражда и поддържа безмастни мускули</purpose>
        <purpose international_code="AK40">Максимизира производството на енергия</purpose>
        <purpose international_code="K50">Стимулира хидратацията на мускулните клетки</purpose>
        <purpose international_code="VM90">Пред- и след- тренировъчно захранване</purpose>
        <purpose international_code="G60">Мускулен растеж</purpose>
        <purpose international_code="AB20">По-голям обем, повече сила и мощ</purpose>
        <purpose international_code="E10">Драматично повишаване на издръжливостта и подобряване на постиженията</purpose>
        <purpose international_code="AB01">Увеличава експлозивната енергия</purpose>
        <purpose international_code="K99">Ускорява възстановяването</purpose>
    </purposes>
    <packings_types>
        <packing_types pid="P01">прах</packing_types>
        <packing_types pid="Т02">таблетки</packing_types>
        <packing_types pid="F03">течност</packing_types>
    </packings_types>
</shop>
